# Config Version
version: 1.0

# debug messages
debug: false


#Skin Data
customModelData:
  DIAMOND_SWORD:
    CoolSword: 1
    AnotherCoolSword: 2

  # You can add more materials here
  # Example:
  # IRON_SWORD:
  #   YetAnotherCoolSword: 3
  #   AndAnotherOne: 4

# message cooldown for every message in seconds
messageCooldown: 1

# Error Show Permission Required Message
errorShowPermission: true

# Messages
messages:
  prefix: "&7[&6ItemSkinChanger&7] &r"
  noPermission: "&eYou do not have permission to use this command."
  requiredPermission: "&cRequired permission: %s"
  usage: "&eUsage: /itsc <subcommand> [arguments]"
  invalidSubcommand: "&cInvalid subcommand. Use /itsc set <customModelDataName>, /itsc clear, or /itsc reload"
  mustHoldItem: "&cYou must be holding an item to use this command."
  customModelDataSet: "&aCustom model data set to %s for the item in your hand."
  customModelDataNotExist: "&cThe custom model data does not exist for this item material."
  customModelDataCleared: "&aCustom model data cleared for the item in your hand."
  customModelDataNoPermission: "&cYou do not have permission to set this custom model data."
  itemNoCustomModelData: "&cThe item in your hand does not have custom model data."
  NotOwner: "&cYou are not the owner of this item."
  pluginReloaded: "&aPlugin and configuration reloaded."




