name: ItemSkinChanger
version: '${version}'
main: org.yusaki.itemskinchanger.ItemSkinChanger
api-version: '1.20'
folia-supported: true
author: Yusaki
description: Change the Skin of Items with Custom Model Data with commands.

commands:
  itsc:
    description: Main command for ItemSkinChanger
    usage: /itsc <subcommand> [arguments]
    tab-completion: true

permissions:
  itemskinchanger.reload:
    description: Allows using reload command
    default: op
  itemskinchanger.setmodeldata:
    description: Allows using /itsc set <modeldata> command
    default: op
  itemskinchanger.setmodeldata.*:
    description: Allows setting any custom model data
    default: op
  itemskinchanger.clearmodeldata:
    description: Allows clearing any custom model data
    default: op